# Generated by Django 4.1.2 on 2022-10-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='naziwsko',
            new_name='nazwisko',
        ),
    ]
