# Generated by Django 4.1.2 on 2022-10-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_naziwsko_osoba_nazwisko'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ('nazwisko',)},
        ),
    ]
