# Generated by Django 4.1.2 on 2022-10-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_osoba_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=33)),
                ('kraj', models.TextField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='osoba',
            name='druzyna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.druzyna'),
        ),
    ]
