# Generated by Django 4.1.2 on 2022-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='can_view_other_persons',
            field=models.BooleanField(default=False),
        ),
    ]
